app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/jdbc-example
      username: postgres
      password: 123456
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always
